### ISSUE TITLE
Datepicker on focus

### ISSUE THREAD

**Issue by Anmo** [sapo/Ink#420]
I have a input with a datepicker UI and when I focus it the callback `onSetDate` triggers.

And the `onSetDate` should have and argument (or an instance property) that says if the trigger is call by direct user interaction or by JS (method `setDate`).

**Comment by fabiosantoscode** [comment]
I think the real bug here is that `onSetDate` is being called as the picker is opened, which is incorrect and useless.

**Comment by fabiosantoscode** [comment]
<3
