### ISSUE TITLE
RequireJS and Ink

### ISSUE THREAD

**Issue by j0hny666** [sapo/Ink#423]
Hi guys, awesome work with Ink. I use it regullary on multiple projects.

Recently I started using RequireJS and the whole AMD concept. I am still pretty new to this problematics. Now I'm trying to use RequireJS and Ink in one project. I understand that Ink has its own module loader simillar to RequireJS.

Is there a way to use these two alongside with each other like this:
1. Load Ink with RequireJS with shimming (exports attribute)

2.Still be able to use classes and data attributes, so that I dont have to load single modules for every ink-dismiss on every page. Basically what I want is to load few of the commonly used modules on every page load and attach them automatically to classes (like autoload.js does). Less frequently used modules can be loaded by requireModules.

Thanks for responses and ceers!

**Comment by j0hny666** [comment]
Ok, I just found out that simly using require on autoload.js enables the Ink functionality, just like <script src="autoload.js"> does, so that is resolved for me :-)

But just out of curiosity - what is the best practice in setup like this?

**Comment by fabiosantoscode** [comment]
requireModules is not AMD-compatible. In AMD, modules can be anonymous, and are defined by URLs. In Ink, every module must have a name, and their name is a dotted path.

You may have luck with monkey patching the `require` function into loading both AMD modules and Ink modules, but ultimately these simply weren't designed to work together.

You mention using autoload.js to enable Ink functionality.

Autoload.js works by creating UI widgets on elements with certain classes. For example, just by adding `ink-modal` to a `div` you're making that `div` an Ink modal, as long as you use autoload.js. You'll notice most examples on the site have their javascript preceded with a "you don't need this if you're using autoload.js" note.

**Comment by j0hny666** [comment]
Hello Fabio,

thank for a fast response! Indeed the autoload.js now works like a charm. I was just curious why other approach didn't work before I tried autoload and you have satisfied that curiosity :-) Thanks again!
