### ISSUE TITLE
Alert dismiss button not respecting $ink-class-prefix

### ISSUE THREAD

**Issue by moroswitie** [sapo/Ink#426]
Changing the sass _$ink-class-prefix_ does not work for the dismiss button on the alert boxes
* **What were you trying to accomplish?**
I tried changing 
`$ink-class-prefix : ink !default;`
into
`$ink-class-prefix : newname !default;`

* **What results did you expect, instead of what you see now?**
I expected all sass files to respect this new class prefix, but instead I realized that the alerts.scss had hardcoded class prefix references

I didn't have the time to fork so here are the effected files
```
src\sass\mixins\_alerts.scss
src\sass\modules\_alerts.scss
src\sass\themes\_alerts.scss
```

* **How to resolve this issue**
Change
`.ink-dismiss`
into
`.#{$ink-class-prefix}-dismiss` 

* **What version of Ink are you using?**
3.1.4

**Comment by pedrocorreia** [comment]
Hi @moroswitie, thanks for catching that one. I'll fix it and i'll be in the next release.

**Comment by twheel** [comment]
`src\sass\themes\_alerts.scss` still contains `ink-dismiss` on line 26 (Ink version 3.1.10).

Also, `src/js/Ink/UI/Close/1/lib.js` and `src/js/Ink/UI/Modal/1/lib.js` contain hard-coded references to `ink-dismiss`, `ink-close`, `ink-alert`, and `ink-alert-block`.
