### ISSUE TITLE
Appended and prepended inputs bug

### ISSUE THREAD

**Issue by NilAndNull** [sapo/Ink#432]
By going to:
http://ink.sapo.pt/ui-elements/forms/?phone=&name=#block-forms

You get the Search word not centered. Something strange with the padding-right, although the padding-rig and padding-left have the same value. 

I've annex a picture, so you can see what I've seen.

![Bug Picture](https://cloud.githubusercontent.com/assets/10235058/6609319/daa02578-c847-11e4-9abe-1df1f031057e.png)

I'm using Google Chrome and Mac OS X. But same issue with Safari.

**Comment by mAiNiNfEcTiOn** [comment]
@NilAndNull

If you apply to both the button and the span the input
```css
flex-grow:1;
flex-shrink: 0;
```

**Comment by fabiosantoscode** [comment]
Looks okay in Firefox. Although I can reproduce this in Chrome, too.

**Comment by pedrocorreia** [comment]
Well i've noticed from this issue that those are completely broken in IE9 and maybe others, so I'll work on those first. But as a workaround as @mAiNiNfEcTiOn said, adding ```flex-shrink: 0``` to the element, fixes this issue.

**Comment by gnpfonseca** [comment]
Thx for the hint @mAiNiNfEcTiOn :) It will be deployed on the next release.

The IE9 bug was related with a missing include in ink-legacy. It's fixed now aswell in 4d82c2b9092fbd4fa4ede95a4df7d2acf4e9a937
