### ISSUE TITLE
Symbols Bug

### ISSUE THREAD

**Issue by NilAndNull** [sapo/Ink#433]
By going here:
http://ink.sapo.pt/ui-elements/forms/?phone=&name=#block-forms

You see:
![Bug Picture](https://cloud.githubusercontent.com/assets/10235058/6609341/1411fa5c-c848-11e4-9747-25c7c64de6d9.png)

Basically the icon is not vertically centered. Neither of them. 

I'm using Google Chrome and Mac OS X. But same issue with Safari.

**Comment by fabiosantoscode** [comment]
Can also reproduce on Firefox

**Comment by gnpfonseca** [comment]
Thx for reporting @NilAndNull . The fix will be deployed on our next release.
