### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by Asuza** [sapo/Ink#438]
In the documentation for [Labels and badges](http://ink.sapo.pt/ui-elements/typography/#labels-and-badges), the "yellow" class is not listed as a valid option.

Additionally, the yellow label in the Demo box has the text "red label" instead of "yellow label".

If it matters, the listed CSS classes aren't in the same order as the examples in the Demo boxes.

**Comment by fabiosantoscode** [comment]
Acknowledged. If our CSS angels don't get there first, I'll fix that one

**Comment by pedrocorreia** [comment]
Thanks @Asuza.
