### ISSUE TITLE
Smooth scroller não remove a class "active" dos links originais

### ISSUE THREAD

**Issue by ivogomes** [sapo/Ink#448]
Use case, tenho uma <ul> de links com smooth scroll. Se clicar em 2 ou 3 desse links, eles ficam todos com a class "active". Ao clicar um link, deveria remover a class "active" dos outros links dentro do mesmo container/listagem

**Comment by fabiosantoscode** [comment]
Thanks! Foi fixed em develop, no commit 3307687.
