### ISSUE TITLE
ink-dismiss das janelas modais faz desaparecer o botão

### ISSUE THREAD

**Issue by ivogomes** [sapo/Ink#449]
Nas janelas modais, a utilização de um elemento com a class "ink-dismiss" faz com que esse elemento depois de clicado desapareça do DOM. 

A modal fecha normalmente, mas se a voltar a abrir, o botão de fechar já lá não está.

**Comment by fabiosantoscode** [comment]
Vamos fazer uma release amanhã ou depois com isto
