### ISSUE TITLE
Install instructions need updating for Ubuntu 14.04

### ISSUE THREAD

**Issue by rcarmo** [sapo/Ink#453]
The installation instructions for node + npm + grunt fail on Ubuntu 14.04 LTS

In particular, grunt fails to find the `nodejs` binary installed from the PPA, since it is expecting a `node` binary as specified in its hashbang.

When this gets fixed, I'll contribute a `Dockerfile` that will neatly run the lot :)

**Comment by fabiosantoscode** [comment]
What do you suggest? Chris Lea's PPA is outdated.

**Comment by rcarmo** [comment]
Using the version of node shipping with Ubuntu 14.04, for one thing (it works), and fixing the install instructions overall.

**Comment by ajscarvalho** [comment]
@rcarmo compiling node from source is an option which I'll take any day, until it becomes more feature complete, stable, etc...

And currently there is at least one module out there that I use that requires more recent versions of npm than the one distributed with Ubuntu, so even if I didn't want it, I was forced to install a newer version.

Incidently the module that needs a newer npm is a PHP composer module.

**Comment by rcarmo** [comment]
> On 07 Jul 2015, at 09:21, Alexandre Amaral de Carvalho <notifications@github.com> wrote:
> 
> @rcarmo <https://github.com/rcarmo> compiling node from source is an option which I'll take any day, until it becomes more feature complete, stable, etc...
> 
Yeah, well, no. My main point here is to have a one-shot, re-usable set of instructions that works on the current Ubuntu LTS so that newcomers can get started without issues or getting into bleeding-edge rebuilds of all the turtles in the Universe.

My secondary point is that if that is fixed, we can use Travis (or other CI) to run builds, automated tests, the works, and that I will also be able to build a Docker container that will let me build custom versions of Ink without littering my hard disk with grunt junk and Ruby packages I have no use for (not to mention node).
> And currently there is at least one module out there that I use that requires more recent versions of npm than the one distributed with Ubuntu, so even if I didn't want it, I was forced to install a newer version
> 
Well, then you’re not in the mainstream :)

But the container approach would also work for you - even better, actually.
