### ISSUE TITLE
triggering a parsing of a DOM node at an arbitrary time

### ISSUE THREAD

**Issue by hickscorp** [sapo/Ink#455]
Hello,

Let's say that you have a DOM that gets populated based on some user events. The page first loads, Ink applies javascript to it, and then for example the user can click a button which will generate DOM nodes.

How can i apply Ink to those newly created nodes? Specifically, i would like to be able to have navigation submenu parsed.

Right now, we have a single-page AngularJS based application. It loads views lazily, meaning that when Ink parses the DOM at page load, most of the UI isn't here for now.
When the user navigates the application, some `<nav ... />` blocks are appended to the DOM, however the `submenu` based items are not working; because Ink didn't add its magic to it yet.
We are writing a set of directives to enable that, but we were unable to find any API in Ink that would allow us to apply navigation related functions to a specific DOM node that just got loaded.

Maybe exposing an `Ink.init(domNode)` would be a good idea. **In the meantime, what should we call instead?**

Thank you for your time and keep up the hard work!

**Comment by fabiosantoscode** [comment]
It's as easy as you think!

Autoload used to be a simple run-and-forget script, but now it's also an Ink module. The `Ink.init` function you speak of it [is in that module and it's called `run`](http://ink.sapo.pt/javascript/Ink.Autoload/#Ink_Autoload-Ink_Autoload-run). Here's an example:

```
Ink.requireModules(['Ink.Autoload_1'] /* ,... */, function(Autoload /* , ... */) {
    // Do your lazyloading stuff...
    Autoload.run(myFreshDomNode);
});
```

Then, `myFreshDomNode`'s whole subtree gets Ink magic. It's the exact same function we call when the document is loaded to load all the Ink modules. The only difference is that we call it on the `document` ;).

**Comment by hickscorp** [comment]
@fabiosantoscode Thanks for your answer.

It's obvious now... I of course missed the documentation on Autoload. IMO, there should be more emphasis about this, as not having this set up obviously is a no-go for most MVC javascript frameworks with a parallel digest / deferred loading.

I am still having problems, the appearing popup with subitem class is truncated to just one element. No idea why.

For future reference, here is how to get it done with AngularJS (The following snippets are coffee / HAML, but it will be quite easy for people to translate back to their favorite language):

First of all, create a directive that will be in charge of deferred-applying Ink to the views:

```coffee
angular.module('myApp.directives')
.directive 'inkDeferred', ->
  return {
    restrict: 'AEC'
    link:     (scope, element, attrs) ->
      Ink.requireModules [ 'Ink.Autoload' ], (Autoload) ->
        console.log 'DEFERED!'
        Autoload.run element
}
```

The directive will basically look for any of those (And no, the fact that the directive is named `inkDeferred` while the expected tag is `ink-deferred` is not a bug. That's regular AngularJS behavior):

- An HTML tag like `<ink-deferred />`
- An CSS class like `<div class='ink-deferred'>`
- An HTML attribute like `<div ink-deferred />`.

Then inside the view that will be loaded later, just tag the top-level HTML element like so:

```haml
%some-tag{ 'ink-deferred': true }
  %p At this point,everything under this div will see itself applied with the Ink javascript if needed, without having to re-apply it to your whole DOM.
```

**Comment by rogeriopvl** [comment]
hey @hickscorp are you still having issues with this? Maybe you could provide a jsbin or plunker showing a simpler scenario where this issue is happening.

We also use Angular here at SAPO, and we haven't had any similar issues. Maybe it's a very specific scenario, so an example would help a lot :)

**Comment by fabiosantoscode** [comment]
To help further clarify, autoload only runs when the DOM is ready. If angular can update things before autoload sees them (the order in which they are included may matter), autoload will initialise everything as you expect it to. Only things that are inserted after the document is loaded are going to need it.

**Comment by hickscorp** [comment]
@rogeriopvl Here's a plunker: http://plnkr.co/edit/9C86sxuwoNwlUyZnERgA?p=preview
Bear with me on the plunkr.... i tried to extract the relevant tags from our project and change then a little bit, but i think the problem is here.

**Comment by rogeriopvl** [comment]
@hickscorp I get "plunkr not found" when I click the link

**Comment by hickscorp** [comment]
@rogeriopvl Hm did you click the link from the email you received? If yes, click the link directly on the Github issue please.

**Comment by rogeriopvl** [comment]
@hickscorp the problem appears to be the `clearfix` class in the `<header>` tag. If you remove it, the menu doesn't get truncated by the element below.

**Comment by hickscorp** [comment]
@rogeriopvl Thanks for your answer, the `clearfix` class was indeed the problem!
