### ISSUE TITLE
Multi-column dropdown menu in Ink?

### ISSUE THREAD

**Issue by twheel** [sapo/Ink#458]
How would one go about creating a multi-column dropdown menu?  Example: 
![screenshot-2015-09-02-13 15 12](https://cloud.githubusercontent.com/assets/3870415/9638430/b8511e1c-5174-11e5-9b83-cbd3b3e0456d.jpg)

**Comment by gnpfonseca** [comment]
Closing this issue. Since it isn't a real issue. You can check all about multi-column layouts in our grid section at http://ink.sapo.pt/ui-elements/grid/#dividing-space.

**Comment by twheel** [comment]
It's more of a support question than an issue, but I understood that support questions should be posted as github issues?

The link you posted doesn't address the question, which is how to make a multi-column dropdown menu (not just layout) with Ink.  Are there examples you could point to?

**Comment by pedrocorreia** [comment]
I think that what @gnpfonseca meant is that you can simply use the grid elements and some simple css tweaks to create the dropdown you need, but here's an example i crafted in a couple of minutes.

https://jsfiddle.net/yyjq4qy1/2/

**Comment by twheel** [comment]
Thank you!
