### ISSUE TITLE
Any WordPress Theme using SAPO Ink?

### ISSUE THREAD

**Issue by kevinkoosk** [sapo/Ink#461]
SAPO Ink is a great theme. I use it for one of my sites... but now I'm moving to Wordpress, and I wonder whether there are any plans to develop a Wordpress theme using SAPO Ink? This is quite important, because almost one-third of the world's websites are using Wordpress as CMS... at least, by their own reckoning. But also, Wordpress brings plugins and modularity. I hope that the SAPO Ink team can consider making a WP theme. Thanks.

**Comment by pedrocorreia** [comment]
Hi @kevinkoosk, Ink is an open source web framework, and as such our focus is in creating tools that make the work of, for instance, developing a wordpress theme faster and easier. So, at this moment theme creation is out of the project's scope.
