### ISSUE TITLE
Modal window call by button :: How to callback OnShow ?

### ISSUE THREAD

**Issue by locas13** [sapo/Ink#462]
Hello,

I want to catch a onShow callback event (options.onShow in documentation) when you show modal window called by button click.

I tried several solutions but none of them works ... would you give me an example please?

Thank you in advance,

Best regards

**Comment by pedrocorreia** [comment]
Hi @locas13,

Is this what you're trying to do? 
http://jsfiddle.net/2jdku6k9/
