### ISSUE TITLE
FormValidator.I18n doesnt change my language.

### ISSUE THREAD

**Issue by ModdyLP** [sapo/Ink#465]
Hello,

I need some help with the Language Injector. I want to set some phrases for the Formvalidator with the Language Code 'de_DE'. But all i made doesnt show the result i want.

`
		Ink.requireModules(['Ink.UI.FormValidator_2','Ink.Util.I18n_1'], function(I18n,FormValidator) {
			var i18n = new FormValidator({}, getI18n().append({ 'de_DE': {
				'formvalidator.generic_error' : '{field} ist falsch',
				'formvalidator.required' : 'Dieses {field} ist erforderlich',
				'formvalidator.min_length': 'The {field} must have a minimum size of {param1} 
                                characters',
				'formvalidator.max_length': 'The {field} must have a maximum size of {param1}
                                 characters',
				'formvalidator.exact_length': 'The {field} must have an exact size of {param1}
                                characters',
				'formvalidator.email': 'The {field} must have a valid e-mail address',
				'formvalidator.url': 'The {field} must have a valid URL',
				'formvalidator.ip': 'The {field} does not contain a valid {param1} IP address',
				'formvalidator.phone': 'The {field} does not contain a valid {param1} phone 
                                number',
				'formvalidator.credit_card': 'The {field} does not contain a valid {param1} credit 
                                 card',
				'formvalidator.date': 'The {field} should contain a date in the {param1} format',
				'formvalidator.alpha': 'The {field} should only contain letters',
				'formvalidator.text': 'The {field} should only contain alphabetic characters',
				'formvalidator.latin': 'The {field} should only contain alphabetic characters',
				'formvalidator.alpha_numeric': 'The {field} should only contain letters or 
                                numbers',
				'formvalidator.alpha_dash': 'The {field} should only contain letters or dashes',
				'formvalidator.digit': 'The {field} should only contain a digit',
				'formvalidator.integer': 'The {field} should only contain an integer',
				'formvalidator.decimal': 'The {field} should contain a valid decimal number',
				'formvalidator.numeric': 'The {field} should contain a number',
				'formvalidator.range': 'The {field} should contain a number between {param1} 
                                 and {param2}',
				'formvalidator.color': 'The {field} should contain a valid color',
				'formvalidator.matches': 'The {field} should match the field {param1}'
			}}));
		});`
The Loading and Declaration works, but than it says "getI18n.append is not a function".
Can you help me with this?

Best regards
ModdyLP

**Comment by pedrocorreia** [comment]
Hi @ModdyLP, sorry for the late reply. It turns out that you found a design flaw where the append dictionary is not being set into the Form Validators prototype and hence is not presence in it's instances.

We've created a quick fix and will be redoing the module in an upcoming release.

https://jsfiddle.net/qqbunjm0/1/

**Comment by ModdyLP** [comment]
Thank you for your replay but i had found the solution on myself by doing some random stuff that i think it will be logically and hey it works.

**Comment by pedrocorreia** [comment]
Cool, glad it turned out ok for you!
