### ISSUE TITLE
Link classes don't work

### ISSUE THREAD

**Issue by lepegadore** [sapo/Ink#466]
I was trying to use 
`<a href="#" class="visited">Test</a>`
`<a href="#" class="active">Test</a>`
`<a href="#" class="hover">Test</a>`
visited, hover, active, normal classes are in DOCS [http://ink.sapo.pt/ui-elements/typography/](Typography Docs)
But it seems like they don't work at all...

**Comment by pedrocorreia** [comment]
Hi @lepegadore those are not "normal" css classes. 
These are pseudo classes and are built into css and we just styled them.
You can read about pseudo classes here: https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes
