### ISSUE TITLE
Aligning Images Center

### ISSUE THREAD

**Issue by dschinkel** [sapo/Ink#468]
How should I be aligning images center in a column?  Do I use some attributes from Ink or just standard css?  I've tried adding push-center to various areas but no luck.  This is from a React.js component.

I'm looking for something similar to this example using Twitter Bootstrap: http://jsfiddle.net/vxad5/1/

This is my first time really trying to use Ink, so not sure how correct this is in terms of using the lib:

```
<div className="column-group">
    <div id='ft-companyDetail-header' cssClass="all-100">
        <div className="panel">
            <img src="/lib/assets/devmynd/devmynd-team.png" />
        </div>
        <div>
            <img src="/lib/assets/devmynd/logo.png" cssClass="push-center" />
        </div>
    </div>
</div>
```

**Comment by dschinkel** [comment]
well this works but please code review this and let me know if this seems like the right way to be using Ink

```
<div className="column-group">
    <div id='ft-companyDetail-header' cssClass="all-100">
        <div className="panel">
            <img src="/lib/assets/devmynd/devmynd-team.png" />
        </div>
        <div className="column-group xlarge-push-center large-push-center medium-push-center small-push-center tiny-push-center">
            <img src="/lib/assets/devmynd/logo.png"/>
        </div>
    </div>
</div>
```

**Comment by pedrocorreia** [comment]
Hi @dschinkel.

Well if i did understand from your example using bootstrap, you're dividing a "row" into thirds and the middle column contains an image, right?

Here's how I'd do it: https://jsfiddle.net/ozzge24h/1/

3 one third width columns and the middle holds a centered image. Note the ```align-center```class that sets the containers ```text-align``` property to ```center```.

If you don't really need the 3 1/3 columns just use full width ```x-100 align-center```classes like in this example: https://jsfiddle.net/ozzge24h/2/

Hope this helps!

**Comment by dschinkel** [comment]
Not quite, I'm not trying to 3rd it however that's interesting, what would be the benefit in doing so vs. just all-100 align-center?  I'll roll with all-100 align-center for how but thanks much for the different examples.  I wish there were more examples.

**Comment by dschinkel** [comment]
I'll close this with what I went with just in case anyone's interested.  Notice I added the missing x-100 suggested by pedrocorreia although it worked without specifying that but I assume it's good practice to make sure that's there.

```
<div className="column-group  large-half-horizontal-gutters">
    <div id='ft-companyDetail-header' cssClass="all-100">
        <div className="panel">
            <img src={this.store.value()[0].headerImageUrl} />
        </div>
        <div className="all-100 align-center">
            <img src={this.store.value()[0].logoUrl}/>
        </div>
        <div className="all-100 align-center">
            <p className="align-center">Source: {this.store.value()[0].interview.source}</p>
            <p className="align-center"><strong>Interviewed on</strong>: {this.store.value()[0].interview.date}</p>
        </div>
    </div>
</div>
```

**Comment by pedrocorreia** [comment]
Yes, you're absolutely right the all-100 is redundant since all block level elements have 100% width by default, I just used to use it because when I start to create a new layout I usually got for the x-large screen sizes and go down from there. So eventually the all-100 becomes something else.

Glad I could be of help @dschinkel.
