### ISSUE TITLE
Demos Don't Seem to Be Working

### ISSUE THREAD

**Issue by dschinkel** [sapo/Ink#470]
I'm using Chrome.  When I try to interact with any of the demos on this page, no matter what section (breadcrumbs, pills, whatever) it jumps to Home and anchors me to the top..so I don't actually see anything working in the demos

http://ink.sapo.pt/ui-elements/navigation/#

**Comment by pedrocorreia** [comment]
Hi @dschinkel,

All of the navigation interaction os based on hovering elements, so no clicking is required to see things work.

On another note the way we implemented the navigation documentation with these "fake" links is wrong and should be corrected, even if only to not take the page back to the top, which is pretty annoying.

**Comment by dschinkel** [comment]
ok makes sense.  I guess I figured clicking on some of those menus and links should do something but yea you're just talking about hover effects only there...
