### ISSUE TITLE
Determing/Changing Main Content Div Width for Desktop Screen

### ISSUE THREAD

**Issue by dschinkel** [sapo/Ink#471]
I'm viewing my page from Chrome from a Macbook Pro 15 retina laptop.  What I'm trying to do is shrink the width of my content to stay within a default of 1261 for desktop I guess large screen?? or all-100% ??

How is INK determining my width here?  

**Cookbook**

I see one of the examples in your cookbook is set to 1370, far more than 1261 default:

<img width="1666" alt="screen shot 2016-06-25 at 4 17 07 pm" src="https://cloud.githubusercontent.com/assets/338798/16359187/7f4b0248-3af0-11e6-9ece-c2b5dda12853.png">

**Now on my site**

I see there are media props set in ink.css:

![content-width-css](https://cloud.githubusercontent.com/assets/338798/16359010/12719074-3aeb-11e6-9619-2d5604bdce45.png)

but why is my width 1334?

![content-width](https://cloud.githubusercontent.com/assets/338798/16359004/cc7e55c0-3aea-11e6-8b11-db1cdf2dd2ca.png)

I even took the main content ``<div>`` out:

![content-width-no-content](https://cloud.githubusercontent.com/assets/338798/16359163/95abe72e-3aef-11e6-86c3-98e5cf11ec75.png)

**What I'd like to have**

I used a tool to demonstrate what I'm looking for, so I created that blue box below to show you what I'm trying to get to.

I would like to narrow the width to the 1261.  So I'd want my content to stay within the blue. Right now the content wrapper div is the 1334 which is outside that area:

<img width="1665" alt="screen shot 2016-06-25 at 4 26 35 pm" src="https://cloud.githubusercontent.com/assets/338798/16359222/d9c183cc-3af1-11e6-8b25-bb932d780e41.png">

Here's the index.html:

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="/lib/ink-3.1.10/css/ink-flex.min.css">
        <link rel="stylesheet" type="text/css" href="/lib/ink-3.1.10/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="/lib/css/master.css" />
        <style>
            .panel {
                border-radius: 2px;
                -webkit-box-shadow: #dddddd 0 1px 1px 0;
                -moz-box-shadow: #dddddd 0 1px 1px 0;
                box-shadow: #dddddd 0 1px 1px 0;
                padding: 1em;
                border: 1px solid #BBB;
                background-color: #FFF;
            }

            footer {
                height: 120px;
                margin-top: 0;
            }

            .wrap {
                min-height: 100%;
                height: auto !important;
                height: 100%;
                margin: 0 auto -120px;
                overflow: auto;
            }
        </style>

    </head>
    <body>
        <div class="ink-grid">
            <header class="vertical-space">
                <div class="column-group">
                    <div class="xlarge-push-left large-push-left all-50">
                        <a href="#">
                            <img src="lib/assets/logo-circles-med2.png" alt="logo" />
                        </a>
                    </div>
                    <div class="align-right all-50">
                        <a href="https://trello.com/b/KR67QinZ" class="small" target="_blank">
                            Feedback <img src="lib/assets/thought-cloud.png" alt="feedback" />
                        </a>
                    </div>
                </div>
            </header>
            <div id="app"></div>
            <script type="text/javascript" src="/scripts/app.bundle.js"></script>
        </div>
        <footer class="clearfix">
            <div class="ink-grid">
                <ul class="unstyled inline half-vertical-space">
                    <li class="active"><a href="#">About</a></li>
                    <li><a href="#">Contact</a></li>
                    <li><a href="#">Would You Like to be Interviewed?</a></li>
                </ul>
                <p class="note">Copyright &copy; 2016 by Dave Schinkel.  All Rights Reserved.</p>
            </div>
        </footer>
    </body>
</html>
```

master.css (_I know it's not perfect yet_)

```
@base: #F7F7F7;
@red: #C23033;
@blue: #003471;
@blue-med: #187fb0;
@blue-light: #97d9f0;
@purple: #a121c4;
@purple-light: #cd97ec;
@grey-xlight:  #E1E1E1;
@grey: #E1E1E1;
@grey-dark: #747474;
@grey-xdark: #464646;
@yellow: #e6d713;
@yellow-dark: #e6d713;
@green: #3fb34f;
@green-med: #689d50;

@brown: #b7986f;


html, body {
  color: #000000;
  background: @base;
  height: 100%;
}

a {
  color: #f36e09
}

a:hover {
  color: #000000;
  text-decoration: underline;
}

td {
  padding: 4px;
}

.italic {
  font-style: italic;
}

//change this to use INK's unstyled and also use INK's hyperlink style for a
ul {
  margin: 0;
  padding: 0;
  list-style-type: none;
}

// move this to be a pseudo class inside ul?
li {
  .arrow{
    content: "";
    border-color: transparent #111;
    border-style: solid;
    border-width: 0.35em 0 0.35em 0.45em;
    display: block;
    height: 0;
    width: 0;
    left: -1em;
    top: 0.9em;
    position: relative;
  }
}

footer {
  background: #000;
}

.bold {
  font-weight: bold;
}

//#home:hover{
//  border-right: 1px solid @red;
//  border-left: 1px solid @red;
//}

.ink-navigation a:hover {
  text-decoration:none;
}

//.underline-grey {
//  border-bottom: 3px solid @grey-xdark;
//}

.underline-black:hover {
  border-bottom: 3px solid black;
}

.underline-grey:hover {
  border-bottom: 3px solid @grey-xdark;
}

.underline-red:hover {
  border-bottom: 3px solid @red;
}

.underline-blue:hover {
  border-bottom: 3px solid @blue-med;
}

.underline-green:hover {
   border-bottom: 3px solid @green;
 }

.underline-yellow:hover {
  border-bottom: 3px solid @yellow;
}

.underline-purple:hover {
  border-bottom: 3px solid @purple;
}

.underline-brown:hover {
  border-bottom: 3px solid @brown;
}

.padding-top-50 {
  padding-top: 50px;
}

.padding-top-30 {
  padding-top: 50px;
}

.padding-top-20{
  padding-top: 20px;
}

.padding-bottom-5{
  padding-bottom: 5px;
}

.padding-bottom-10{
  padding-bottom: 10px;
}

.padding-bottom-50{
  padding-bottom: 50px;
}

.padding-bottom-200{
  padding-bottom: 200px;
}

.padding-bottom-300{
  padding-bottom: 300px;
}

.padding-left-10{
  padding-left: 10px;
}

.padding-left-30{
  padding-left: 30px;
}

.padding-left-50{
  padding-left: 50px;
}

.padding-left-100{
  padding-left: 100px;
}

.padding-right-5{
  padding-right: 5px;
}

.padding-right-15{
  padding-right: 15px;
}

.vertical-align-middle{
  vertical-align: middle;
}

.margin-2{
  margin: 2px;
}

.font-22 {
  font-size: 22px;
}

// change this to just be called black
.font-black{
  color: #000000;
}

.grey {
  color: @grey
}

.grey-dark {
  color: @grey-dark
}

.blue {
  color: @blue
}

.blue-light {
  color: @blue-light
}

.green {
  color: @green
}

.brown {
  color: @brown
}

.yellow {
  color: @yellow
}

.purple{
  color: @purple
}

.red{
  color: @red
}

.purple-light{
  color: @purple-light
}

.xsmall{
  font-size: 16px;
}

.inline{
  display: inline;
}

td.top{
  vertical-align: text-top;
}

tr.border-bottom-grey {
  border-bottom: 1px solid @grey;
}
// components
.section-heading {
  border-bottom: 1px solid #979797;
}

.bottom-border-grey-veryLight {
  border-bottom: 1px solid @grey;
}

.ink-navigation ul.menu.horizontal li a {
  padding: .5em 2em .5em 0em;
  display: block;
  line-height: 1.7;
}

//nav
#home:hover {
  color: @red;
}
```

(_fyi don't freak, I have some inline styles because I'm playing around with it.  It'll be moved to LESS later on_)

I see in your docs you talk about the 1261:

Our default layout breakpoints are:

```
tiny for screens widths up to 320px.
small for screen widths between 321 and 640 pixels.
medium for screen widths between 641 and 960 pixels.
large for screen widths between 961 and 1260 pixels.
xlarge for screen widths above 1261 pixels.
```

but in my case I'm not specifying any xlarge or any of that.  So just trying to figure out what sets the default width here for my container and what's pushing it out to 1334.  Shouldn't the media query keep it to within 1261 here?:

![content-media](https://cloud.githubusercontent.com/assets/338798/16359117/64cdbd54-3aee-11e6-976b-cf68801d9f48.png)

**Comment by dschinkel** [comment]
Ok it looks like these two divs are determining the total width:

<img width="1666" alt="screen shot 2016-06-25 at 3 44 44 pm" src="https://cloud.githubusercontent.com/assets/338798/16359039/0f833a74-3aec-11e6-9af1-7edaac2179ce.png">

<img width="1674" alt="screen shot 2016-06-25 at 3 45 00 pm" src="https://cloud.githubusercontent.com/assets/338798/16359042/1f701f56-3aec-11e6-9ba8-4513e980359b.png">

**Comment by dschinkel** [comment]
Posting (rubber ducking) as I go.  Ok if I wrap the INK grid in a div and tell it max-width of 1261 it works but it feels hacky??

So I added the max-width to my wrap div:

```
            .wrap {
                min-height: 100%;
                height: auto !important;
                height: 100%;
                margin: 0 auto -120px;
                overflow: auto;
                **max-width: 1261px;**
            }
```
<img width="1668" alt="screen shot 2016-06-25 at 4 33 46 pm" src="https://cloud.githubusercontent.com/assets/338798/16359259/0c387ca6-3af3-11e6-9bc2-2d4ed09ca7b5.png">

**Comment by pedrocorreia** [comment]
hi @dschinkel, 

The grid (site) width is determined by the ```.ink-grid ```class. 

It's set by default do ```width: 100%; max-width: 1440px;```

You can override that to any value you like in your own css, or you can download our sources and setup the build tools and create a custom build of your own.

If you choose the second option you can find the ```$grid-max-width```sass variable in ```src/sass/config/_grid.scss```. Just change that value to whatever you like and recompile de css.

I hope this helps.

**Comment by pedrocorreia** [comment]
You can also completely redefine the breakpoints if you wish, in the same file:

```
$grid-breakpoints: (
    ('screen', 'xlarge', 1261px, null, 2em, 1.08em, false),
    ('screen', 'large', 961px, 1260px, 1.75em, 1.05em, true),
    ('screen', 'medium', 641px, 960px, 1.5em, 1em, false),
    ('screen', 'small', 321px, 640px, 1.25em, .98em, false),
    ('screen', 'tiny', null, 320px, 1em, .97em, false)
);
```

each line translates to:
```
('screen', 'classPrefix', min-width, max-width, gutter-width, base-font-size, is-grid-for-older-browsers),
```

Just change it to meet your requirements and recompile.

**Comment by dschinkel** [comment]
thanks for the input!  I think I'd rather not tweak the core INK sass.  Having my own custom style to do that instead works for now.  Also I'm trying to start using the API.  Here I'm trying to set the offset for options but  not getting the syntax right, I tried: ``new Ink.UI.Sticky(el, [options.offsetTop: 50]);`` also tried new ```new Ink.UI.Sticky(el, [options.offsetTop= 50]);``` also new ```new Ink.UI.Sticky(el, [offsetTop: 50]);``` and ```new Ink.UI.Sticky(el, [offsetTop=50])```;

It's not clear to me how to pass options.  Yes I see options is an object, but where do you get that object and how do you pass that into the options array properly?  Can you verify how I'd pass offsetTop properly in the above?

**Comment by dschinkel** [comment]
thanks, good stuff to know!

**Comment by dschinkel** [comment]
For now I'm going to simply use max-width on my main div.  I'd rather try to override than to change core sass of INK.
