### ISSUE TITLE
all-100 doesn't push out to full width

### ISSUE THREAD

**Issue by dschinkel** [sapo/Ink#475]
all-100 isn't pushing out to the full width, does this just not work in INK?

```
<div className="column-group">
    <div className="all-100 align-center fw-300 xlarge-70">
        Interested in being included? blah blah blah blah
    </div>
</div>
```

I ended up having to add a width:100% to it.

**Comment by gnpfonseca** [comment]
You want all the breakpoints to have 100% width except the xlarge, right? Cause that xlarge class will override your all-100 for site widths above 1261px.

**Comment by dschinkel** [comment]
I see, ok thanks!!
