### ISSUE TITLE
Node 6.4.0 Breaks Ink

### ISSUE THREAD

**Issue by dschinkel** [sapo/Ink#476]
#I am pretty sure that after updating to Node 6.4.0 it broke Ink.  Is Ink compatible with this version of Node yet?  I had some Ink stuff working just fine right before I upgraded.  Now it's bombing.

<img width="614" alt="screen shot 2016-08-30 at 11 07 17 pm" src="https://cloud.githubusercontent.com/assets/338798/18115648/a6db5fca-6f06-11e6-9b0b-edfa7457909e.png">

This code now breaks in my application:

```
        setTimeout(() => {
            const el = ReactDOM.findDOMNode(this);
            if(el && document.getElementById("interviewHeading")) {
                new Ink.UI.Sticky(el, {topElement: "#interviewHeading", bottomElement: "#footer"});
            }
        }, 100);
```

**Comment by mariomc** [comment]
Node version shouldn't at all affect the functionality of the framework.
By the stack trace, check if you're trying to attach a component to an unattached DOM node. Or if document.body is present. Follow the stack until you reach the root of the problem.

**Comment by dschinkel** [comment]
found out actually another middleware broke after doing an npm update.  Disregard.
