### ISSUE TITLE
Issues with Next button of date picker

### ISSUE THREAD

**Issue by selarom-epilef** [sapo/Ink#477]
I am currently using the latest version of ink and I have encountered a problem with the date picker. Basically, if the day 31st of any month is selected, and if also the next month does not have up to 31 days, the Next button (» by default) will not work anymore.

This also happens with the prev button as well. My guess is that it tries to find the day 31 on September and simply fails.

**Comment by gnpfonseca** [comment]
Can´t reproduce. I suppose you are using ink v3.1.10 which is the latest, right? If you can share a code example for debuging would be great. Also, what browser are you using?
