### ISSUE TITLE
IE 8 Errors out on missing Ink.Util.Validator_1 module

### ISSUE THREAD

**Issue by dschinkel** [sapo/Ink#478]
I'm getting the following error in Windows 7, IE 8.  I assume I need a polyfill?  Or do I need to do something like this:
```
    componentDidMount: function(){
        setTimeout(() => {
            Ink.requireModules(
                [
                    'Ink.Dom.Loaded_1',
                    'Ink.Dom.Event_1',
                    'Ink.Net.Ajax_1',
                    'Ink.Util.Validator_1'
                ]);
        }, 100);
    }
```
(just trying it in a react component first to see if it fixes the problem which it did not).

<img width="766" alt="screen shot 2016-09-06 at 11 18 17 pm" src="https://cloud.githubusercontent.com/assets/338798/18301426/e26e17fe-7496-11e6-8527-c383d0fdd47f.png">

<img width="982" alt="screen shot 2016-09-07 at 12 38 14 am" src="https://cloud.githubusercontent.com/assets/338798/18300988/72aa9db4-7493-11e6-9e63-55758b2311ba.png">

**Comment by mariomc** [comment]
Since you're using react: https://facebook.github.io/react/blog/2016/01/12/discontinuing-ie8-support.html

**Comment by dschinkel** [comment]
hmm did not see that yet.  thanks.
