### ISSUE TITLE
What Happened?

### ISSUE THREAD

**Issue by dschinkel** [sapo/Ink#489]
If this repo is no longer supported please take down the website so people know.  Why didn't you update the READ.me and put something on your site if it's no longer supported/active?

**Comment by dschinkel** [comment]
Please, just take this entire repo down and retire it.  You need to be explicit if this project is dead in the readme.

![Screen Shot 2020-05-05 at 2 05 09 AM](https://user-images.githubusercontent.com/338798/81042045-e48cba80-8e74-11ea-98c1-c4d9cd6e93dc.jpg)

**Comment by pedrocorreia** [comment]
Hi again @dschinkel.

The as you have noticed new feature development has halted indefinitely. How ever it doesn't mean that it's not maintained. Obviously, it's severely understaffed, so we do what we can.

However, this being an open source project, you can fork it, change it and develop and propose new features.

As to the error in your screenshot I cannot replicate it. If you could provide more information maybe i'd be able to help.
