### ISSUE TITLE
ssl on your cdn not working 

### ISSUE THREAD

**Issue by dschinkel** [sapo/Ink#490]
What's the deal here?  These are not secure??  So you still have your codebase referencing sub modules using http?  why?  So am I pretty much screwed if I want my site to run https with SAPO now?

https://fastly.ink.sapo.pt/3.1.10/js/autoload.js
https://fastly.ink.sapo.pt/3.1.10/css/ink.min.css
https://fastly.ink.sapo.pt/3.1.10/js/ink-all.min.js

![Screen Shot 2020-05-05 at 2 01 01 AM](https://user-images.githubusercontent.com/338798/81041781-4b5da400-8e74-11ea-9334-f6a0e19dbcde.jpg)

![Screen Shot 2020-05-05 at 1 55 09 AM](https://user-images.githubusercontent.com/338798/81041438-78f61d80-8e73-11ea-9d01-2e234ce3b538.jpg)

![Screen Shot 2020-05-05 at 2 06 39 AM](https://user-images.githubusercontent.com/338798/81042148-1736b300-8e75-11ea-9787-f3247b93ca38.jpg)

![Screen Shot 2020-05-05 at 1 53 30 AM](https://user-images.githubusercontent.com/338798/81041343-3fbdad80-8e73-11ea-9d5d-ad1d8b83bfad.jpg)

**Comment by pedrocorreia** [comment]
Hi @dschinkel, if you notice in the documentation:

![image](https://user-images.githubusercontent.com/219789/81197085-c7acd000-8fb7-11ea-8fe1-03f8d72effc3.png)

That domain (fastly.ink.sapo.pt) does not serve under SSL and never has.
Sorry if the documentation was confusing in anyway.

**Comment by dschinkel** [comment]
thank you!
